/*
 Base de données de test.
 */
ALTER USER postgres WITH PASSWORD 'password';

DROP TABLE IF EXISTS stories;

CREATE TABLE stories(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    creation_date TIMESTAMP,
    last_edit_date TIMESTAMP);

INSERT INTO stories(title, content, creation_date, last_edit_date)
VALUES
('Test', 'Proin ut lorem vitae diam iaculis sagittis. Phasellus bibendum felis sit amet ante porta, vitae iaculis lacus malesuada. Phasellus pharetra urna tristique neque cursus, non facilisis ligula auctor. Nulla eget nunc et leo molestie blandit. Morbi vitae tellus ipsum. Sed magna magna, facilisis nec elementum vitae, malesuada ac ligula. Proin non lacus nec velit congue iaculis rhoncus posuere est. In egestas ex vitae condimentum semper. Maecenas rutrum risus vitae neque accumsan ullamcorper. Duis nisi nisi, imperdiet non tincidunt condimentum, vestibulum et velit. Etiam tellus purus, ullamcorper eget maximus sit amet, semper eu felis. Vestibulum vitae aliquam enim. Morbi condimentum massa quis velit euismod aliquet. Phasellus varius nisi a eros tristique, id cursus arcu venenatis. Aenean tincidunt, velit non ullamcorper commodo, massa est ullamcorper dui, id rhoncus felis est in nisi. Nunc at blandit sapien.

Morbi commodo, augue vitae lobortis euismod, orci tellus aliquam ligula, non luctus arcu neque ac erat. In ac turpis ex. Etiam scelerisque at felis at consequat. Praesent bibendum, erat sed dictum ullamcorper, justo augue aliquam lorem, laoreet gravida odio velit in odio. Praesent leo nisi, egestas vitae augue eu, sagittis scelerisque sapien. Fusce efficitur eros enim, posuere cursus lectus viverra in. Curabitur eu volutpat augue. Integer odio justo, placerat ac orci id, tempus euismod lacus. Vestibulum placerat bibendum elit, non pretium ipsum lobortis placerat.

Vivamus tristique purus at velit feugiat ultrices. Vivamus tincidunt tortor id erat sollicitudin, et varius ipsum vestibulum. Maecenas lorem arcu, scelerisque nec ullamcorper vel, bibendum sagittis dolor. Vivamus nec neque id dolor hendrerit placerat. Curabitur pretium enim leo, a ultrices mi tempus varius. Nulla nec eros sed ligula vulputate aliquam ac quis eros. Pellentesque cursus, nisl sit amet fermentum commodo, felis dui sollicitudin justo, nec laoreet felis velit et felis. Sed nec orci luctus, consectetur neque sed, elementum risus. Nam id felis eros. In hac habitasse platea dictumst. Donec interdum lacinia lorem condimentum dapibus. Morbi enim ipsum, imperdiet at lobortis nec, vehicula non dolor. Donec fermentum metus ut dictum blandit. Cras malesuada id nisl non viverra. Quisque consequat ex a mauris consectetur tristique. Vestibulum eget tortor lectus.

Aenean sed mauris orci. In sit amet urna nec elit dictum consequat a in arcu. Aenean mattis tincidunt turpis, nec convallis enim bibendum at. Curabitur varius diam diam, eu congue neque vulputate et. Curabitur a vehicula massa, non tristique arcu. Maecenas eget turpis eu magna efficitur condimentum. Cras ante risus, scelerisque id lectus quis, egestas tempus orci. Mauris eu augue et ligula accumsan sodales in in mauris. Aenean urna ligula, sagittis vitae faucibus quis, fermentum eu lorem. Aliquam vitae sapien urna. Pellentesque neque lacus, faucibus euismod nibh ut, varius dignissim tellus.

Donec tempus non nibh a vestibulum. Mauris eu eros a dui scelerisque vulputate. Cras venenatis commodo ullamcorper. Praesent vel porttitor lectus. Phasellus faucibus dolor sit amet nisi bibendum, et venenatis mi interdum. Aenean faucibus ornare gravida. Nulla mollis vel nulla a dictum. Aenean id porttitor ante. Nullam a sem nec elit vulputate tempus. Curabitur nec libero arcu. Duis neque urna, porttitor vel quam vitae, porttitor bibendum turpis. Phasellus vehicula fringilla mollis. Nunc in aliquam nisl, et placerat nibh. Cras a molestie augue.

Fusce pellentesque magna ut elementum egestas. In congue ac ligula quis venenatis. Curabitur porttitor vel lorem ut feugiat. Donec ut velit consequat ipsum egestas mattis nec aliquet purus. Donec convallis nec nisi et porttitor. Duis et tincidunt nibh. Nullam tempor dolor at risus iaculis placerat. Nunc vel nunc eget ligula sagittis vehicula. Proin sed porta ante, a suscipit odio. Pellentesque finibus tortor eget faucibus gravida. Proin vitae lorem lectus. Aenean ornare in lacus quis molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Curabitur blandit imperdiet leo, a elementum nisi elementum in. Quisque cursus hendrerit elit sit amet tempus. Aenean at nunc varius, iaculis tellus ac, pulvinar ante. Fusce aliquet tincidunt lectus, eu facilisis lacus vehicula sed. Pellentesque vel convallis nibh. Aenean eget mauris eget sem suscipit interdum. Nullam suscipit magna eu erat dapibus pretium. Nunc mauris leo, porta in ipsum vel, tincidunt faucibus felis. Cras hendrerit id urna sed porttitor.

Donec a mi finibus, facilisis sem et, eleifend arcu. Morbi sit amet felis mauris. Curabitur justo mi, bibendum et feugiat eget, varius nec velit. Suspendisse laoreet condimentum maximus. Duis mollis elit sed metus suscipit tristique. Vivamus et auctor libero, in consectetur erat. Aliquam mauris dolor, tempus eget feugiat vitae, hendrerit et leo. Morbi a sem dui. Duis lacus turpis, mattis vitae malesuada eget, fringilla at mi. Morbi iaculis libero tincidunt bibendum tincidunt.', NOW(), NOW()),
('Test2', 'Ut ipsum quam, maximus sed vehicula nec, dictum in orci. Fusce sit amet lectus ut purus sagittis consectetur. Curabitur a erat dolor. Vestibulum eget neque sed orci scelerisque semper vel quis risus. Nullam quis auctor dolor. Mauris euismod semper interdum. In urna nisl, lobortis nec enim dignissim, rhoncus elementum ex. Donec sit amet libero varius, porttitor mauris ac, tincidunt augue. Proin enim mauris, posuere non mauris sed, porta ultrices mi. Integer nec leo ligula. Suspendisse eu nibh pulvinar, scelerisque lorem in, congue massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus velit lacus, elementum vitae risus non, sodales pretium eros. Etiam elit dui, varius nec mauris vel, porta cursus tortor.

Phasellus iaculis luctus felis, sed pulvinar purus auctor id. Curabitur in sollicitudin diam, at mollis ligula. Vestibulum faucibus ut libero eget dictum. Nunc vel rutrum velit. Aenean ultrices sodales mauris, sit amet commodo felis rhoncus mattis. Ut auctor venenatis odio, ac suscipit velit gravida non. Sed eleifend hendrerit purus, a pharetra quam vulputate at.

Nullam mollis elit sit amet hendrerit lacinia. Pellentesque interdum tellus lorem, vitae fermentum tortor facilisis sit amet. Aliquam vestibulum faucibus augue id congue. In finibus elit justo, quis condimentum augue pulvinar a. Pellentesque eu purus vestibulum, semper nisl eget, vehicula diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam tincidunt ante ut gravida efficitur. Integer porta felis dapibus, dapibus eros vitae, euismod erat. Sed feugiat enim sed magna luctus, eget congue justo faucibus. Vivamus at dignissim urna, vel congue odio. Integer pretium sit amet nisi eget suscipit. In eu scelerisque enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam efficitur ligula nibh, et porta turpis blandit id. Integer laoreet odio purus, non molestie elit vehicula eget. Duis sem mi, ultrices sit amet risus a, euismod porttitor metus.

Proin a mi molestie, eleifend neque et, vehicula sem. Vestibulum vitae orci consequat, porttitor sapien et, ullamcorper velit. Sed tempus accumsan tellus, a pellentesque mauris sollicitudin quis. Aliquam in pretium nunc. Cras sit amet tellus fermentum urna euismod pretium id non nulla. Praesent pulvinar, lacus at facilisis tempor, nisi tellus eleifend odio, at tincidunt elit massa ut lorem. Nulla a quam dui. Aenean accumsan sagittis lobortis. Nulla at interdum leo, nec semper neque. Curabitur eleifend, arcu et laoreet iaculis, nunc lorem tincidunt sem, quis fringilla tortor ligula ut lectus. Vestibulum ut lorem odio. Nullam auctor libero nibh, ac pretium magna fermentum vel.

Sed luctus diam vitae nibh accumsan, sit amet ultricies nunc varius. Duis dui lorem, mattis eu lacus id, euismod faucibus augue. Proin eu lectus ipsum. Sed lacus erat, pulvinar vel auctor in, semper quis neque. Praesent in ligula quis diam pellentesque dictum non ac mi. Morbi eu rhoncus dui, ut dictum ligula. Vestibulum accumsan eros vel posuere vulputate. Sed et tempus augue.

Nulla at velit maximus, viverra diam et, luctus urna. Donec quis velit id odio porttitor ultrices. Nunc ullamcorper imperdiet erat non viverra. Praesent gravida, erat a convallis laoreet, lorem eros scelerisque turpis, at vulputate elit dui at turpis. Maecenas et augue lacinia urna maximus vestibulum. Morbi rutrum auctor felis vitae suscipit. Sed vel neque mollis, scelerisque ex quis, posuere tellus. Suspendisse maximus risus id purus tempor bibendum. In hac habitasse platea dictumst.

Donec placerat nisl quis scelerisque pulvinar. Praesent venenatis commodo purus in pulvinar. Donec sit amet consectetur neque. Sed lobortis lacinia quam, eget pharetra elit posuere sit amet. Donec sollicitudin scelerisque luctus. Etiam vel orci vel felis eleifend accumsan. Cras efficitur molestie ligula, sit amet tristique nisl ultricies nec. Aenean eleifend velit velit, eget dictum arcu ultrices quis.

Sed venenatis odio non sem aliquet vehicula. Cras dapibus felis sed auctor semper. Donec id odio consequat, blandit nulla nec, auctor lorem. Ut non arcu libero. Morbi tortor erat, eleifend eget lorem vel, molestie sodales mi. Suspendisse potenti. Curabitur consectetur porta nulla. Donec sed diam odio. Sed pulvinar interdum erat. Ut lobortis non sapien vitae tempor. Vivamus magna justo, consequat ac dolor vel, maximus hendrerit mi. Suspendisse potenti. Vestibulum at elementum nibh.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras mollis sit amet orci a ornare. Integer vitae elit vel eros imperdiet congue. Aliquam ultricies ipsum in ullamcorper imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non est vitae dui volutpat volutpat. Fusce at ipsum et dui volutpat tincidunt. Mauris dui lacus, efficitur id turpis vitae, venenatis venenatis arcu. Mauris suscipit mattis turpis non vehicula. Quisque blandit ornare purus sed blandit. Donec sit amet volutpat ligula duis.', NOW(), NOW());